GET http://localhost:3000/user

###     getting a user by id
GET http://localhost:3000/user/609b7dd2c4271727606f3f12

###     adding a user
POST http://localhost:3000/user
Content-Type: application/json

{
  "name" : "Max",
  "email":"max@gmail.com"
}

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "name" : "Sam",
  "email":"sam@gmail.com"
}


###
POST http://localhost:3000/user
Content-Type: application/json

{
  "name" : "Yash",
  "email":"yash@gmail.com"
}


###

DELETE http://localhost:3000/user/609b7dd2c4271727606f3f12


###

PUT http://localhost:3000/user/609b7dd5c4271727606f3f13
Content-Type: application/json

{
  "name": "trit"
}